# Generated by Django 4.2.6 on 2023-10-27 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='views_count',
            new_name='view_count',
        ),
    ]
